// certificats HTTPS pour envoi secure à thingspeak
// Ne pa soublier #define TS_ENABLE_SSL (see thingspeak-arduino @ github)
// DigiCert High Assurance EV Root CA

 #define SECRET_TS_ROOT_CA \
"-----BEGIN CERTIFICATE-----\n" \
"MIIDgDCCAmigAwIBAgIQNerH/sDRZ3n9Yvcpt60igTANBgkqhkiG9w0BAQsFADBI\n" \
"MRswGQYDVQQDDBJFU0VUIFNTTCBGaWx0ZXIgQ0ExHDAaBgNVBAoME0VTRVQsIHNw\n" \
"b2wuIHMgci4gby4xCzAJBgNVBAYTAlNLMB4XDTIyMDYzMDA5NDIxN1oXDTMyMDYy\n" \
"NzA5NDIxN1owSDEbMBkGA1UEAwwSRVNFVCBTU0wgRmlsdGVyIENBMRwwGgYDVQQK\n" \
"DBNFU0VULCBzcG9sLiBzIHIuIG8uMQswCQYDVQQGEwJTSzCCASIwDQYJKoZIhvcN\n" \
"AQEBBQADggEPADCCAQoCggEBAN3XvsuwGuJDYyciXcaGG5kyxCPTO9m55OvEu45X\n" \
"KCFiFXAEZPJYWeKptzQfv/RO5hPgIWDHfQPE5fb+61pV7w9dGue3mErg3Zw6DjDN\n" \
"PFk5YYzHlCRlSSocxuuFdKPMnuTPNkPSv8nmoYelhTpNfDRX5TVMml83bXB/ISYL\n" \
"O5SSpvhg0GSJtnJeZZOk5qXpImJr6/Im1BlQaMq8cbE944NPFfaDy3bSpdiTGv8Z\n" \
"WxRsuFiiJLjQ2Xs9HJYw8HUJeI9BBFZZZWpw7HGZaqlW1ADxl8qv3Kwduxb0CsV7\n" \
"R+5Utghg40c0i67bs5vE4IzdqrPrDtNNOx4d3/e7l58/4I8CAwEAAaNmMGQwDgYD\n" \
"VR0PAQH/BAQDAgIEMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFGgdMYoY\n" \
"0JSXdYADatVZUf/UZRpzMB8GA1UdIwQYMBaAFGgdMYoY0JSXdYADatVZUf/UZRpz\n" \
"MA0GCSqGSIb3DQEBCwUAA4IBAQBDGPrqHrG9OCSE8sVC2+yqijcuyGg7EZmEejPU\n" \
"Ev/+Elt6FoYBfSK9b961uVQ61KnDOIOHdm1GAthn2LwroAHCscOg/6Spb6XYybo6\n" \
"otwdt354rEeswh2rJWlwy8F1BUTZKT05XmgzrdSBJEVOcapv1VsmGqLz0aa8tnWw\n" \
"BlXrTXmvBSQRjiKhmv2X3BC/FT/ir8TWxQPyxC6cJTGvN/E3+dCHJsGYBZEzHT60\n" \
"H/PWuDp9B/7BsKHSba/frTqrjnMvGVgyAMy+4DFlqdb8O1tZUke5DBJJ7DmPRYRM\n" \
"AuD9BRS2uo03jjoCMB+8qW/0zyV531BRu8l6+PlNvQW8dZV3\n" \
"-----END CERTIFICATE-----\n";


/**********************************************************************

const char* rootCACertificate1 = \
  "-----BEGIN CERTIFICATE-----\n" \
  "MIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBs\n" \
  "MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\n" \
  "d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j\n" \
  "ZSBFViBSb290IENBMB4XDTA2MTExMDAwMDAwMFoXDTMxMTExMDAwMDAwMFowbDEL\n" \
  "MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3\n" \
  "LmRpZ2ljZXJ0LmNvbTErMCkGA1UEAxMiRGlnaUNlcnQgSGlnaCBBc3N1cmFuY2Ug\n" \
  "RVYgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMbM5XPm\n" \
  "+9S75S0tMqbf5YE/yc0lSbZxKsPVlDRnogocsF9ppkCxxLeyj9CYpKlBWTrT3JTW\n" \
  "PNt0OKRKzE0lgvdKpVMSOO7zSW1xkX5jtqumX8OkhPhPYlG++MXs2ziS4wblCJEM\n" \
  "xChBVfvLWokVfnHoNb9Ncgk9vjo4UFt3MRuNs8ckRZqnrG0AFFoEt7oT61EKmEFB\n" \
  "Ik5lYYeBQVCmeVyJ3hlKV9Uu5l0cUyx+mM0aBhakaHPQNAQTXKFx01p8VdteZOE3\n" \
  "hzBWBOURtCmAEvF5OYiiAhF8J2a3iLd48soKqDirCmTCv2ZdlYTBoSUeh10aUAsg\n" \
  "EsxBu24LUTi4S8sCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQF\n" \
  "MAMBAf8wHQYDVR0OBBYEFLE+w2kD+L9HAdSYJhoIAu9jZCvDMB8GA1UdIwQYMBaA\n" \
  "FLE+w2kD+L9HAdSYJhoIAu9jZCvDMA0GCSqGSIb3DQEBBQUAA4IBAQAcGgaX3Nec\n" \
  "nzyIZgYIVyHbIUf4KmeqvxgydkAQV8GK83rZEWWONfqe/EW1ntlMMUu4kehDLI6z\n" \
  "eM7b41N5cdblIZQB2lWHmiRk9opmzN6cN82oNLFpmyPInngiK3BD41VHMWEZ71jF\n" \
  "hS9OMPagMRYjyOfiZRYzy78aG6A9+MpeizGLYAiJLQwGXFK3xPkKmNEVX58Svnw2\n" \
  "Yzi9RKR/5CYrCsSXaQ3pjOLAEFe4yHYSkVXySGnYvCoCWw9E1CAx2/S6cCZdkGCe\n" \
  "vEsXCS+0yx5DaMkHJ8HSXPfqIbloEpw8nL+e/IBcm2PN7EeqJSdnoDfzAIJ9VNep\n" \
  "+OkuE6N36B9K\n" \
  "-----END CERTIFICATE-----\n";
  
const char* rootCACertificate2 = \
     "-----BEGIN CERTIFICATE-----\n" \
     "MIIDSjCCAjKgAwIBAgIQRK+wgNajJ7qJMDmGLvhAazANBgkqhkiG9w0BAQUFADA/\n" \
     "MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT\n" \
     "DkRTVCBSb290IENBIFgzMB4XDTAwMDkzMDIxMTIxOVoXDTIxMDkzMDE0MDExNVow\n" \
     "PzEkMCIGA1UEChMbRGlnaXRhbCBTaWduYXR1cmUgVHJ1c3QgQ28uMRcwFQYDVQQD\n" \
     "Ew5EU1QgUm9vdCBDQSBYMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\n" \
     "AN+v6ZdQCINXtMxiZfaQguzH0yxrMMpb7NnDfcdAwRgUi+DoM3ZJKuM/IUmTrE4O\n" \
     "rz5Iy2Xu/NMhD2XSKtkyj4zl93ewEnu1lcCJo6m67XMuegwGMoOifooUMM0RoOEq\n" \
     "OLl5CjH9UL2AZd+3UWODyOKIYepLYYHsUmu5ouJLGiifSKOeDNoJjj4XLh7dIN9b\n" \
     "xiqKqy69cK3FCxolkHRyxXtqqzTWMIn/5WgTe1QLyNau7Fqckh49ZLOMxt+/yUFw\n" \
     "7BZy1SbsOFU5Q9D8/RhcQPGX69Wam40dutolucbY38EVAjqr2m7xPi71XAicPNaD\n" \
     "aeQQmxkqtilX4+U9m5/wAl0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNV\n" \
     "HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFMSnsaR7LHH62+FLkHX/xBVghYkQMA0GCSqG\n" \
     "SIb3DQEBBQUAA4IBAQCjGiybFwBcqR7uKGY3Or+Dxz9LwwmglSBd49lZRNI+DT69\n" \
     "ikugdB/OEIKcdBodfpga3csTS7MgROSR6cz8faXbauX+5v3gTt23ADq1cEmv8uXr\n" \
     "AvHRAosZy5Q6XkjEGB5YGV8eAlrwDPGxrancWYaLbumR9YbK+rlmM6pZW87ipxZz\n" \
     "R8srzJmwN0jP41ZL9c8PDHIyh8bwRLtTcm1D9SZImlJnt1ir/md2cXjbDaJWFBM5\n" \
     "JDGFoqgCWjBH4d1QB7wCCZAA62RjYJsWvIjJEubSfZGL+T0yjWW06XyxV3bqxbYo\n" \
     "Ob8VZRzI9neWagqNdwvYkQsEjgfbKbYK7p2CNTUQ\n" \
     "-----END CERTIFICATE-----\n"; 
     
const char* rootCACertificate3 = \
  "-----BEGIN CERTIFICATE-----\n" \
  "MIIDtzCCAp+gAwIBAgIQDOfg5RfYRv6P5WD8G/AwOTANBgkqhkiG9w0BAQUFADBl\n" \
  "MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\n" \
  "d3cuZGlnaWNlcnQuY29tMSQwIgYDVQQDExtEaWdpQ2VydCBBc3N1cmVkIElEIFJv\n" \
  "b3QgQ0EwHhcNMDYxMTEwMDAwMDAwWhcNMzExMTEwMDAwMDAwWjBlMQswCQYDVQQG\n" \
  "EwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNl\n" \
  "cnQuY29tMSQwIgYDVQQDExtEaWdpQ2VydCBBc3N1cmVkIElEIFJvb3QgQ0EwggEi\n" \
  "MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCtDhXO5EOAXLGH87dg+XESpa7c\n" \
  "JpSIqvTO9SA5KFhgDPiA2qkVlTJhPLWxKISKityfCgyDF3qPkKyK53lTXDGEKvYP\n" \
  "mDI2dsze3Tyoou9q+yHyUmHfnyDXH+Kx2f4YZNISW1/5WBg1vEfNoTb5a3/UsDg+\n" \
  "wRvDjDPZ2C8Y/igPs6eD1sNuRMBhNZYW/lmci3Zt1/GiSw0r/wty2p5g0I6QNcZ4\n" \
  "VYcgoc/lbQrISXwxmDNsIumH0DJaoroTghHtORedmTpyoeb6pNnVFzF1roV9Iq4/\n" \
  "AUaG9ih5yLHa5FcXxH4cDrC0kqZWs72yl+2qp/C3xag/lRbQ/6GW6whfGHdPAgMB\n" \
  "AAGjYzBhMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW\n" \
  "BBRF66Kv9JLLgjEtUYunpyGd823IDzAfBgNVHSMEGDAWgBRF66Kv9JLLgjEtUYun\n" \
  "pyGd823IDzANBgkqhkiG9w0BAQUFAAOCAQEAog683+Lt8ONyc3pklL/3cmbYMuRC\n" \
  "dWKuh+vy1dneVrOfzM4UKLkNl2BcEkxY5NM9g0lFWJc1aRqoR+pWxnmrEthngYTf\n" \
  "fwk8lOa4JiwgvT2zKIn3X/8i4peEH+ll74fg38FnSbNd67IJKusm7Xi+fT8r87cm\n" \
  "NW1fiQG2SVufAQWbqz0lwcy2f8Lxb4bG+mRo64EtlOtCt/qMHt1i8b5QZ7dsvfPx\n" \
  "H2sMNgcWfzd8qVttevESRmCD1ycEvkvOl77DZypoEd+A5wwzZr8TDRRu838fYxAe\n" \
  "+o0bJW1sj6W3YQGx0qMmoRBxna3iw/nDmVG3KwcIzi7mULKn+gpFL6Lw8g==\n" \
  "-----END CERTIFICATE-----\n";

const char* rootCACertificate4 = \
  "-----BEGIN CERTIFICATE-----\n" \
  "MIID6TCCAtGgAwIBAgIQOoBzw4dgryEQ2mrccNRj9DANBgkqhkiG9w0BAQsFADBI\n" \
  "MRswGQYDVQQDDBJFU0VUIFNTTCBGaWx0ZXIgQ0ExHDAaBgNVBAoME0VTRVQsIHNw\n" \
  "b2wuIHMgci4gby4xCzAJBgNVBAYTAlNLMB4XDTIyMDcwNTAwMDAwMFoXDTIzMDgw\n" \
  "MzIzNTk1OVowbzELMAkGA1UEBhMCVVMxFjAUBgNVBAgTDU1hc3NhY2h1c2V0dHMx\n" \
  "DzANBgNVBAcTBk5hdGljazEcMBoGA1UEChMTVGhlIE1hdGh3b3JrcywgSW5jLjEZ\n" \
  "MBcGA1UEAwwQKi50aGluZ3NwZWFrLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP\n" \
  "ADCCAQoCggEBAMyitDvoy0QujArrZ7BLuKGv2KqqWqsPtXma4sbr9/om6idKgP+F\n" \
  "buY2Dgd05cr4HpVvy+Q0BIVNkALhAN1M2jwbN3UgVkivPW2Yy/RyXp9sWUfQq6dm\n" \
  "7Ow3fyJHRDXkicvNAtdpQyQ/Jy47Uc3Q/46ufbphkQcM/vPCgfzuVvHW4AjjxV8p\n" \
  "y1UzsEBf3S8Fdsr845jMmp9CCMljJh4QjAwMIzR30XOODsssvF1k2GEDhw0BBB3V\n" \
  "x3GVNccuoq1ZjzZlsxjUapmMbaH+3BRdnifn6d5wXNJtUT7eYuhDQWh8bMwtJHSY\n" \
  "JZzGwP4j+x5BZPPnWbPmydsaWUSZYBcxxJkCAwEAAaOBpzCBpDALBgNVHQ8EBAMC\n" \
  "BaAwHQYDVR0OBBYEFIXpW5gOUOw/VfjumI1wi3EsexWGMB8GA1UdIwQYMBaAFGgd\n" \
  "MYoY0JSXdYADatVZUf/UZRpzMCsGA1UdEQQkMCKCECoudGhpbmdzcGVhay5jb22C\n" \
  "DnRoaW5nc3BlYWsuY29tMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAJ\n" \
  "BgNVHRMEAjAAMA0GCSqGSIb3DQEBCwUAA4IBAQA65a5nEOkMcqp8CZD50CcBfmGK\n" \
  "WNeFZXnDbt3zGnfrzP5pgLyusRXqhBw4CZb/Znr7I/ZOJYbMuGABnzFJLLAXMzT8\n" \
  "f76H0ifupLT9nbrs1r3rRDN9aaC/UGhTXXACZjtT04Cs/uvFdd9xGhkV9tpr8jGY\n" \
  "qM1qwLNjOt4iWEfeDLnim6n5tZirpTs4O5bv5q6JaMqmBdIWlKhHVlaE3L3NvMrv\n" \
  "os5hRAEqd0DvTwaMP9UJONHmJkMbfwmqw6ZNQGimwAMTYJTFOL2dqxpj8ijSmaHu\n" \
  "iiPenjuwCUO3EJKO2UiCr2adsqUtcFAmqdMZnRtxZwogN4w2GP5v4+abJVs+\n" \
  "-----END CERTIFICATE-----\n";
  
  const char* rootCACertificate5 = \
  "-----BEGIN CERTIFICATE-----\n" \
  "MIIDgDCCAmigAwIBAgIQNerH/sDRZ3n9Yvcpt60igTANBgkqhkiG9w0BAQsFADBI\n" \
  "MRswGQYDVQQDDBJFU0VUIFNTTCBGaWx0ZXIgQ0ExHDAaBgNVBAoME0VTRVQsIHNw\n" \
  "b2wuIHMgci4gby4xCzAJBgNVBAYTAlNLMB4XDTIyMDYzMDA5NDIxN1oXDTMyMDYy\n" \
  "NzA5NDIxN1owSDEbMBkGA1UEAwwSRVNFVCBTU0wgRmlsdGVyIENBMRwwGgYDVQQK\n" \
  "DBNFU0VULCBzcG9sLiBzIHIuIG8uMQswCQYDVQQGEwJTSzCCASIwDQYJKoZIhvcN\n" \
  "AQEBBQADggEPADCCAQoCggEBAN3XvsuwGuJDYyciXcaGG5kyxCPTO9m55OvEu45X\n" \
  "KCFiFXAEZPJYWeKptzQfv/RO5hPgIWDHfQPE5fb+61pV7w9dGue3mErg3Zw6DjDN\n" \
  "PFk5YYzHlCRlSSocxuuFdKPMnuTPNkPSv8nmoYelhTpNfDRX5TVMml83bXB/ISYL\n" \
  "O5SSpvhg0GSJtnJeZZOk5qXpImJr6/Im1BlQaMq8cbE944NPFfaDy3bSpdiTGv8Z\n" \
  "WxRsuFiiJLjQ2Xs9HJYw8HUJeI9BBFZZZWpw7HGZaqlW1ADxl8qv3Kwduxb0CsV7\n" \
  "R+5Utghg40c0i67bs5vE4IzdqrPrDtNNOx4d3/e7l58/4I8CAwEAAaNmMGQwDgYD\n" \
  "VR0PAQH/BAQDAgIEMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFGgdMYoY\n" \
  "0JSXdYADatVZUf/UZRpzMB8GA1UdIwQYMBaAFGgdMYoY0JSXdYADatVZUf/UZRpz\n" \
  "MA0GCSqGSIb3DQEBCwUAA4IBAQBDGPrqHrG9OCSE8sVC2+yqijcuyGg7EZmEejPU\n" \
  "Ev/+Elt6FoYBfSK9b961uVQ61KnDOIOHdm1GAthn2LwroAHCscOg/6Spb6XYybo6\n" \
  "otwdt354rEeswh2rJWlwy8F1BUTZKT05XmgzrdSBJEVOcapv1VsmGqLz0aa8tnWw\n" \
  "BlXrTXmvBSQRjiKhmv2X3BC/FT/ir8TWxQPyxC6cJTGvN/E3+dCHJsGYBZEzHT60\n" \
  "H/PWuDp9B/7BsKHSba/frTqrjnMvGVgyAMy+4DFlqdb8O1tZUke5DBJJ7DmPRYRM\n" \
  "AuD9BRS2uo03jjoCMB+8qW/0zyV531BRu8l6+PlNvQW8dZV3\n" \
  "-----END CERTIFICATE-----\n";

 
  const char* rootCACertificate6 = \
"-----BEGIN CERTIFICATE-----\n" \
"MIID6TCCAtGgAwIBAgIQOoBzw4dgryEQ2mrccNRj9DANBgkqhkiG9w0BAQsFADBI\n" \
"MRswGQYDVQQDDBJFU0VUIFNTTCBGaWx0ZXIgQ0ExHDAaBgNVBAoME0VTRVQsIHNw\n" \
"b2wuIHMgci4gby4xCzAJBgNVBAYTAlNLMB4XDTIyMDcwNTAwMDAwMFoXDTIzMDgw\n" \
"MzIzNTk1OVowbzELMAkGA1UEBhMCVVMxFjAUBgNVBAgTDU1hc3NhY2h1c2V0dHMx\n" \
"DzANBgNVBAcTBk5hdGljazEcMBoGA1UEChMTVGhlIE1hdGh3b3JrcywgSW5jLjEZ\n" \
"MBcGA1UEAwwQKi50aGluZ3NwZWFrLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP\n" \
"ADCCAQoCggEBAMyitDvoy0QujArrZ7BLuKGv2KqqWqsPtXma4sbr9/om6idKgP+F\n" \
"buY2Dgd05cr4HpVvy+Q0BIVNkALhAN1M2jwbN3UgVkivPW2Yy/RyXp9sWUfQq6dm\n" \
"7Ow3fyJHRDXkicvNAtdpQyQ/Jy47Uc3Q/46ufbphkQcM/vPCgfzuVvHW4AjjxV8p\n" \
"y1UzsEBf3S8Fdsr845jMmp9CCMljJh4QjAwMIzR30XOODsssvF1k2GEDhw0BBB3V\n" \
"x3GVNccuoq1ZjzZlsxjUapmMbaH+3BRdnifn6d5wXNJtUT7eYuhDQWh8bMwtJHSY\n" \
"JZzGwP4j+x5BZPPnWbPmydsaWUSZYBcxxJkCAwEAAaOBpzCBpDALBgNVHQ8EBAMC\n" \
"BaAwHQYDVR0OBBYEFIXpW5gOUOw/VfjumI1wi3EsexWGMB8GA1UdIwQYMBaAFGgd\n" \
"MYoY0JSXdYADatVZUf/UZRpzMCsGA1UdEQQkMCKCECoudGhpbmdzcGVhay5jb22C\n" \
"DnRoaW5nc3BlYWsuY29tMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAJ\n" \
"BgNVHRMEAjAAMA0GCSqGSIb3DQEBCwUAA4IBAQA65a5nEOkMcqp8CZD50CcBfmGK\n" \
"WNeFZXnDbt3zGnfrzP5pgLyusRXqhBw4CZb/Znr7I/ZOJYbMuGABnzFJLLAXMzT8\n" \
"f76H0ifupLT9nbrs1r3rRDN9aaC/UGhTXXACZjtT04Cs/uvFdd9xGhkV9tpr8jGY\n" \
"qM1qwLNjOt4iWEfeDLnim6n5tZirpTs4O5bv5q6JaMqmBdIWlKhHVlaE3L3NvMrv\n" \
"os5hRAEqd0DvTwaMP9UJONHmJkMbfwmqw6ZNQGimwAMTYJTFOL2dqxpj8ijSmaHu\n" \
"iiPenjuwCUO3EJKO2UiCr2adsqUtcFAmqdMZnRtxZwogN4w2GP5v4+abJVs+\n" \
"-----END CERTIFICATE-----\n";

  const char* rootCACertificate7 = \
"\-----BEGIN CERTIFICATE-----\n" \
"MIIDgDCCAmigAwIBAgIQNerH/sDRZ3n9Yvcpt60igTANBgkqhkiG9w0BAQsFADBI\n" \
"MRswGQYDVQQDDBJFU0VUIFNTTCBGaWx0ZXIgQ0ExHDAaBgNVBAoME0VTRVQsIHNw\n" \
"b2wuIHMgci4gby4xCzAJBgNVBAYTAlNLMB4XDTIyMDYzMDA5NDIxN1oXDTMyMDYy\n" \
"NzA5NDIxN1owSDEbMBkGA1UEAwwSRVNFVCBTU0wgRmlsdGVyIENBMRwwGgYDVQQK\n" \
"DBNFU0VULCBzcG9sLiBzIHIuIG8uMQswCQYDVQQGEwJTSzCCASIwDQYJKoZIhvcN\n" \
"AQEBBQADggEPADCCAQoCggEBAN3XvsuwGuJDYyciXcaGG5kyxCPTO9m55OvEu45X\n" \
"KCFiFXAEZPJYWeKptzQfv/RO5hPgIWDHfQPE5fb+61pV7w9dGue3mErg3Zw6DjDN\n" \
"PFk5YYzHlCRlSSocxuuFdKPMnuTPNkPSv8nmoYelhTpNfDRX5TVMml83bXB/ISYL\n" \
"O5SSpvhg0GSJtnJeZZOk5qXpImJr6/Im1BlQaMq8cbE944NPFfaDy3bSpdiTGv8Z\n" \
"WxRsuFiiJLjQ2Xs9HJYw8HUJeI9BBFZZZWpw7HGZaqlW1ADxl8qv3Kwduxb0CsV7\n" \
"R+5Utghg40c0i67bs5vE4IzdqrPrDtNNOx4d3/e7l58/4I8CAwEAAaNmMGQwDgYD\n" \
"VR0PAQH/BAQDAgIEMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFGgdMYoY\n" \
"0JSXdYADatVZUf/UZRpzMB8GA1UdIwQYMBaAFGgdMYoY0JSXdYADatVZUf/UZRpz\n" \
"MA0GCSqGSIb3DQEBCwUAA4IBAQBDGPrqHrG9OCSE8sVC2+yqijcuyGg7EZmEejPU\n" \
"Ev/+Elt6FoYBfSK9b961uVQ61KnDOIOHdm1GAthn2LwroAHCscOg/6Spb6XYybo6\n" \
"otwdt354rEeswh2rJWlwy8F1BUTZKT05XmgzrdSBJEVOcapv1VsmGqLz0aa8tnWw\n" \
"BlXrTXmvBSQRjiKhmv2X3BC/FT/ir8TWxQPyxC6cJTGvN/E3+dCHJsGYBZEzHT60\n" \
"H/PWuDp9B/7BsKHSba/frTqrjnMvGVgyAMy+4DFlqdb8O1tZUke5DBJJ7DmPRYRM\n" \
"AuD9BRS2uo03jjoCMB+8qW/0zyV531BRu8l6+PlNvQW8dZV3\n" \
"-----END CERTIFICATE-----\n";

  *********************************************************************/
